name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Auth Auto Trigger"
        required: true
        default: "warning"
      tags:
        description: "Tag for Manual Retrigger"
        required: true
defaults:
  run:
    working-directory: auth
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: idlefingers/do-space-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: "./auth/dist"
          SPACE_NAME: askorbik/auth/latest
          SPACE_REGION: fra1
          SPACE_ACCESS_KEY_ID: UIYNTAF4BTN6HHDGYETX
          SPACE_SECRET_ACCESS_KEY: dQsg1xn7HRIO3xhj1LBsk/Gc0RY3ITXHTR1H6sjdKB0
