name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Auth Auto Trigger"
        required: true
        default: "warning"
      tags:
        description: "Tag for Manual Retrigger"
        required: true
defaults:
  run:
    working-directory: auth
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.DO_SPACE_ACCESS_KEY}}
          aws-secret-access-key:  ${{secrets.DO_SPACE_SECRET}}
          aws-region: ${{DO_REGION}}    
      - name: List AWS 
        run: aws s3 ls
