name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Auth Auto Trigger"
        required: true
        default: "warning"
      tags:
        description: "Tag for Manual Retrigger"
        required: true
defaults:
  run:
    working-directory: auth
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: idlefingers/do-space-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: "./auth/latest"
          SPACE_NAME: ${{ secrets.DO_SPACE_NAME}}
          SPACE_REGION: ${{ secrets.DO_SPACE_REGION}}
          SPACE_ACCESS_KEY_ID: ${{ secrets.DO_SPACE_ACCESS_KEY}}
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACE_SECRET}}
