name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - "container/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Container Auto Trigger"
        required: true
        default: "warning"
      tags:
        description: "Tag for Manual Retrigger"
        required: true
defaults:
  run:
    working-directory: container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DO_SPACE_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.DO_SPACE_SECRET}}
          aws-region: ${{ secrets.DO_REGION}}
        env:
          SPACE_NAME: ${{ secrets.DO_SPACE_NAME}}
          SPACE_REGION: ${{ secrets.DO_REGION}}
      - run: aws s3 sync dist s3://${SPACE_NAME} \
          --follow-symlinks \
          --delete \
          --endpoint https://${SPACE_REGION}.digitaloceanspaces.com
